#!/bin/bash

CHECKSUM=
HTTPURL="http://sysupgrade.wisnuc.com/NasUpdate/files"
TARBALL="barcelona-sysupgrade-0000-0001.tar"

rm -rf release
svn checkout https://192.168.5.40/svn/PythonWebProject/branches/release --username jiangwei --password 123456 --quiet --no-auth-cache -r 1379

# python/django app only
tar cf aaa.tar -C release/aaa .
mv aaa.tar boot/

#
# tar boot folder
#
tar cf $TARBALL -C boot/ .

CHECKSUM=$( md5sum $TARBALL | awk '{ print $1 }' )

#
# move to ouput folder
#
rm -rf output
mkdir -p output

rm -rf output/${TARBALL}
mv $TARBALL output

echo   "#           source      target"                             >  output/sysupgrade.txt
echo   "REVISION    0           1     "                             >> output/sysupgrade.txt
echo   "#           source      target"                             >> output/sysupgrade.txt
echo   "BOOT        0           1   ${HTTPURL}/${TARBALL}   $CHECKSUM"  >> output/sysupgrade.txt

ls -sail output
cat output/sysupgrade.txt
