#!/bin/bash

CHECKSUM=
HTTPURL="http://sysupgrade.wisnuc.com/NasUpdate/files/"
TARBALL="barcelona-sysupgrade-0000-0001.tar"

rm -rf release
svn checkout https://192.168.5.40/svn/PythonWebProject/branches/release --username jiangwei --password 123456 --quiet --no-auth-cache -r 1378

# python/django app only
tar cf aaa.tar.gz -C release/aaa .
mv aaa.tar.gz boot/

#
# tar boot folder
#
tar cf $TARBALL -C boot/ .

CHECKSUM=$( md5sum $TARBALL | awk '{ print $1 }' )

#
# move to ouput folder
#
rm -rf output
mkdir -p output

mv $TARBALL output

echo   "#           source    target"                               >  output/sysupgrade.txt
echo   "REVISION    0         1     "                               >> output/sysupgrade.txt
echo   "# FILE"                                                     >> output/sysupgrade.txt
echo   "FILE        0         1         $TARBALL        $CHECKSUM"  >> output/sysupgrade.txt

