#!/bin/sh

# prepare dirs for mount point
mkdir p1
mkdir p2

# this cannot fail, otherwise endless reboot
mount -t ext4 /dev/mmcblk0p2 /p2
if [ "$?" -ne 0 ]; then reboot -f; fi

mount -t ext4 /dev/mmcblk0p1 /p1
if [ "$?" -ne 0 ]; then reboot -f; fi

# overwrite netatalk global, fix bad homes section
echo "patch netatalk templates file"
cp /p2/boot/templates/netatalk/global /p1/etc/mininas/templates/netatalk/global

# overwrite python/django server app
echo "replace python/django server app"
rm -rf /p1/srv/mini/aaa
mkdir -p /p1/srv/mini/aaa
busybox tar xf /p2/boot/aaa.tar -C /p1/srv/mini/aaa

echo "update version info, current & next version, as well as status"
echo 1 > /p1/etc/mininas/sysupgrade/curr_version
rm /p1/etc/mininas/sysupgrade/next_version
touch /p1/etc/mininas/sysupgrade/next_version
echo "none" > /p1/etc/mininas/sysupgrade/status
busybox sync

echo ""
echo "====================="
echo "====================="
echo "booting new system..."
echo "====================="
echo ""

rm /p2/boot/cmdline
busybox sync
busybox reboot -f


