#!/bin/sh

# prepare dirs for mount point
mkdir p1
mkdir p2

# this cannot fail, otherwise endless reboot
mount -t ext4 /dev/mmcblk0p2 /p2
if [ "$?" -ne 0 ]; then
    reboot -f
fi

mount -t ext4 /dev/mmcblk0p1 /p1
if [ "$?" -ne 0 ]; then
    # TODO
    reboot -f   
fi

#
# bring up httpd
#
if [ -e "/p2/boot/ipaddr" ]; then
    busybox ifconfig eth0 $(cat /p2/boot/ipaddr) netmask 255.255.255.0 up
    busybox httpd -h /p2/boot/www
fi

STATUS_FILE=/p2/boot/www/status.txt

biecho () {
    
    echo "$1"
    echo "${1}<br>" > $STATUS_FILE
}

# overwrite netatalk global, fix bad homes section
biecho "patch netatalk templates file"
cp /p2/boot/templates/netatalk/global /p1/etc/mininas/templates/netatalk/global


biecho "booting new system..."
rm /p2/boot/cmdline
busybox sync
busybox reboot -f


